/* criação da tabela de uru�rio */
CREATE TABLE USUARIO (
   CPF NUMBER NOT NULL,
   NOME VARCHAR2(32),
   EMAIL VARCHAR2(32),
   SENHA VARCHAR2(32),
   CONSTRAINT PK_USUARIO PRIMARY KEY(CPF) /*definição da chave primária */
);

/* criação da tabela de produto */
CREATE TABLE PRODUTO (
   CODIGO_DE_BARRAS VARCHAR2(48) NOT NULL, /* o tamanho condiz com o tamanho usual de c�digo de barras no brasil */
   NOME_ORIGINAL VARCHAR2(32),
   NOME_TRADUZIDO VARCHAR2(32),
   PRECO NUMBER,
   TIPO VARCHAR2(16) NOT NULL,
   LOJA NUMBER NOT NULL,
   CONSTRAINT PK_PRODUTO PRIMARY KEY(CODIGO_DE_BARRAS), /* definição da chave primária */
   CONSTRAINT CH_PRODUTO CHECK (TIPO = 'FILME' OR TIPO = 'MUSICA' OR TIPO = 'LIVRO' OR TIPO = 'JOGO' OR TIPO = 'PACOTE')
   CONSTRAINT LOJA FOREIGN KEY(LOJA) REFERENCES LOJA(CNPJ) ON DELETE CASCADE
   /* verificação se o tipo do produto diz respeito a uma das possíveis especializações */
);

/* criação da tabela de amizade */
CREATE TABLE AMIZADE (
   USUARIO_1 NUMBER NOT NULL,
   USUARIO_2 NUMBER NOT NULL,
   DATA DATE,
   CONSTRAINT PK_AMIZADE PRIMARY KEY(USUARIO_1, USUARIO_2), /* definição da chave primária */
   CONSTRAINT FK_USUARIO_1 FOREIGN KEY(USUARIO_1) REFERENCES USUARIO(CPF) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT FK_USUARIO_2 FOREIGN KEY(USUARIO_2) REFERENCES USUARIO(CPF) ON DELETE CASCADE,
   CONSTRAINT CK_AMIZADE CHECK (USUARIO_1 < USUARIO_2)
   /* verificação para garantir que uma dupla de usuários nunca se repita */
);

/* criação da tabela de compra */
CREATE TABLE COMPRA (
   COMPRADOR NUMBER NOT NULL,
   DESTINATARIO NUMBER NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   DATA_HORA DATE NOT NULL,
   METODO_PAGAMENTO VARCHAR2(16),
   CONSTRAINT PK_COMPRA PRIMARY KEY(DESTINATARIO, PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_COMPRADOR FOREIGN KEY(COMPRADOR) REFERENCES USUARIO(CPF) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT FK_DESTINATARIO FOREIGN KEY(DESTINATARIO) REFERENCES USUARIO(CPF) ON DELETE CASCADE,
   CONSTRAINT FK_PRODUTO_COMPRA FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE
);

/* criação da tabela de denúncia */
CREATE TABLE DENUNCIA (
   USUARIO NUMBER NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   DATA DATE NOT NULL,
   MOTIVO VARCHAR2(64),
   CONSTRAINT PK_DENUNCIA PRIMARY KEY(USUARIO, PRODUTO, DATA), /* definição da chave primária */
   CONSTRAINT FK_USUARIO_DENUNCIA FOREIGN KEY(USUARIO) REFERENCES USUARIO(CPF) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT FK_PRODUTO_DENUNCIA FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE
);

/* criação da tabela de possui */
CREATE TABLE POSSUI (
   USUARIO NUMBER NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   CONSTRAINT PK_POSSUI PRIMARY KEY(USUARIO, PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_USUARIO_DENUNCIAR FOREIGN KEY(USUARIO) REFERENCES USUARIO(CPF) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT FK_PRODUTO_DENUNCIAR FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE
);

/* criação da tabela de avalia��o */
CREATE TABLE AVALIACAO (
   USUARIO NUMBER NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   DATA DATE,
   NOTA NUMBER,
   COMENTARIO VARCHAR2(64),
   CONSTRAINT PK_AVALIACAO PRIMARY KEY(USUARIO, PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_AVALIACAO FOREIGN KEY(USUARIO, PRODUTO) REFERENCES POSSUI(USUARIO, PRODUTO) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT CK_AVALIACAO CHECK(NOTA >= 0 AND NOTA <= 10) /* a nota de um produto pode estar somente no intervalo de 0 a 10 */
);

/* criação da tabela de pacote */
CREATE TABLE PACOTE (
   PRODUTO VARCHAR2(48) NOT NULL,
   CONSTRAINT PK_PACOTE PRIMARY KEY(PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_PRODUTO_PACOTE FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE /* definição das chaves estrangeiras */
);

/* criação da tabela de cont�m */
CREATE TABLE CONTEM (
   PACOTE VARCHAR2(48) NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   CONSTRAINT PK_CONTEM PRIMARY KEY(PACOTE, PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_PACOTE FOREIGN KEY(PACOTE) REFERENCES PACOTE(PRODUTO) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT FK_PRODUTO_CONTEM FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE
);

/* criação da tabela de m�sica */
CREATE TABLE MUSICA (
   PRODUTO VARCHAR2(48) NOT NULL,
   COMPOSITOR VARCHAR2(32),
   DURACAO NUMBER,
   GENERO VARCHAR2(16),
   CONSTRAINT PK_MUSICA PRIMARY KEY(PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_PRODUTO_MUSICA FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de filme */
CREATE TABLE FILME (
   PRODUTO VARCHAR2(48) NOT NULL,
   DATA_ESTREIA DATE,
   DURACAO NUMBER,
   GENERO VARCHAR2(16),
   FAIXA_ETARIA NUMBER,
   NACIONALIDADE VARCHAR2(16),
   CONSTRAINT PK_FILME PRIMARY KEY(PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_PRODUTO_FILME FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE, /* definição da chave estrangeira */
   CONSTRAINT CK_FILME CHECK(FAIXA_ETARIA = 0 OR FAIXA_ETARIA = 10 OR FAIXA_ETARIA = 12 OR FAIXA_ETARIA = 14 OR FAIXA_ETARIA = 16 OR FAIXA_ETARIA = 18)
   /* a faixa-et�ria segue o sistema de classifica��o brasileiro, portanto, seus valores devem ser limitados a 0 (livre), 10, 12,  14, 16 e 18 */
);

/* criação da tabela de elenco */
CREATE TABLE ELENCO (
   FILME VARCHAR2(48) NOT NULL,
   ATOR_ATRIZ VARCHAR2(32),
   CONSTRAINT PK_ELENCO PRIMARY KEY(FILME, ATOR_ATRIZ), /* definição da chave primária */
   CONSTRAINT FK_ELENCO FOREIGN KEY(FILME) REFERENCES FILME(PRODUTO) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de trailer */
CREATE TABLE TRAILER (
   PRODUTO VARCHAR2(48) NOT NULL,
   DURACAO NUMBER,
   VERSAO NUMBER NOT NULL,
   CONSTRAINT PK_TRAILER PRIMARY KEY(PRODUTO, VERSAO), /* definição da chave primária */
   CONSTRAINT FK_PRODUTO_TRAILER FOREIGN KEY(PRODUTO) REFERENCES FILME(PRODUTO) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de jogo */
CREATE TABLE JOGO (
   PRODUTO VARCHAR2(48) NOT NULL,
   DATA_LANCAMENTO DATE,
   FAIXA_ETARIA NUMBER,
   DESCRITORES_FAIXA_ETARIA VARCHAR2(32),
   DESENVOLVEDOR VARCHAR2(32),
   CONSTRAINT PK_JOGO PRIMARY KEY(PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_PRODUTO_JOGO FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE, /* definição da chave estrangeira */
   CONSTRAINT CK_JOGO CHECK(FAIXA_ETARIA = 0 OR FAIXA_ETARIA = 10 OR FAIXA_ETARIA = 12 OR FAIXA_ETARIA = 14 OR FAIXA_ETARIA = 16 OR FAIXA_ETARIA = 18)
   /* a faixa-et�ria segue o sistema de classifica��o brasileiro, portanto, seus valores devem ser limitados a 0 (livre), 10, 12,  14, 16 e 18 */
);

/* criação da tabela de demo */
CREATE TABLE DEMO (
   JOGO VARCHAR2(48) NOT NULL,
   TEMPO_DISPONIVEL NUMBER,
   VERSAO NUMBER NOT NULL,
   CONSTRAINT PK_DEMO PRIMARY KEY(JOGO, VERSAO), /* definição da chave primária */ 
   CONSTRAINT FK_DEMO FOREIGN KEY(JOGO) REFERENCES JOGO(PRODUTO) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de livro */
CREATE TABLE LIVRO (
   PRODUTO VARCHAR2(48) NOT NULL,
   IDIOMA VARCHAR2(16),
   EDITORA VARCHAR2(16),
   NUMERO_PAGINAS NUMBER,
   SERIE VARCHAR2(16),
   SINOPSE VARCHAR2(100),
   CONSTRAINT PK_LIVRO PRIMARY KEY(PRODUTO), /* definição da chave primária */
   CONSTRAINT FK_PRODUTO_LIVRO FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de autores */
CREATE TABLE AUTOR (
   LIVRO VARCHAR2(48) NOT NULL,
   NOME VARCHAR2(32),
   CONSTRAINT PK_AUTOR PRIMARY KEY(LIVRO, NOME), /* definição da chave primária */
   CONSTRAINT FK_AUTOR FOREIGN KEY(LIVRO) REFERENCES LIVRO(PRODUTO) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de loja */
CREATE TABLE LOJA (
   CNPJ NUMBER NOT NULL,
   NOME VARCHAR2(32),
   EMAIL VARCHAR2(32),
   CONSTRAINT PK_LOJA PRIMARY KEY(CNPJ) /* definição da chave primária */
);

/* criação da tabela para o endere�os das lojas */
CREATE TABLE ENDERECO_LOJA (
    LOJA NUMBER NOT NULL,
    RUA VARCHAR2(32),
    NUMERO NUMBER,
    BAIRRO VARCHAR2(32),
    CEP NUMBER,
    CONSTRAINT PK_ENDERECO PRIMARY KEY(LOJA), /* definição da chave primária */
    CONSTRAINT FK_ENDERECO FOREIGN KEY(LOJA) REFERENCES LOJA(CNPJ) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de funcion�rio */
CREATE TABLE FUNCIONARIO (
   CPF NUMBER NOT NULL,
   NOME VARCHAR2(32),
   EMAIL VARCHAR2(32),
   SENHA VARCHAR2(32),
   CARGO VARCHAR2(16),
   LOJA NUMBER NOT NULL,
   CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CPF, LOJA), /* definição da chave primária */
   CONSTRAINT FK_FUNCIONARIO FOREIGN KEY(LOJA) REFERENCES LOJA(CNPJ) ON DELETE CASCADE /* definição da chave estrangeira */
);

/* criação da tabela de chat */
CREATE TABLE CHAT (
   USUARIO NUMBER NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   FUNCIONARIO NUMBER NOT NULL,
   LOJA NUMBER NOT NULL,
   CONSTRAINT PK_CHAT PRIMARY KEY(USUARIO, PRODUTO, FUNCIONARIO, LOJA), /* definição da chave primária */
   CONSTRAINT FK_USUARIO_CHAT FOREIGN KEY(USUARIO) REFERENCES USUARIO(CPF) ON DELETE CASCADE, /* definição das chaves estrangeiras */
   CONSTRAINT FK_PRODUTO_CHAT FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO_DE_BARRAS) ON DELETE CASCADE,
   CONSTRAINT FK_FUNCIONARIO_CHAT FOREIGN KEY(FUNCIONARIO, LOJA) REFERENCES FUNCIONARIO(CPF, LOJA) ON DELETE CASCADE
);

/* criação da tabela de mensagens */
CREATE TABLE MENSAGENS (
   USUARIO NUMBER NOT NULL,
   PRODUTO VARCHAR2(48) NOT NULL,
   FUNCIONARIO NUMBER NOT NULL,
   LOJA NUMBER NOT NULL,
   CONTEUDO VARCHAR2(100) NOT NULL,
   DATA DATE,
   CONSTRAINT PK_MENSAGENS PRIMARY KEY(USUARIO, PRODUTO, FUNCIONARIO, LOJA, CONTEUDO, DATA), /* definição da chave primária */
   CONSTRAINT FK_MENSAGENS FOREIGN KEY(USUARIO, PRODUTO, FUNCIONARIO, LOJA) REFERENCES CHAT(USUARIO, PRODUTO, FUNCIONARIO, LOJA) /* definição da chave estrangeira */
);